# This is a basic workflow to help you get started with Actions

name: CI

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Install correct version of mingw
        run: |
          choco install qt5-default
          choco install make
      #    choco uninstall mingw --force
      #    choco uninstall strawberryperl --force
      #- uses: numworks/setup-msys2@v1
      #  with:
      #    msystem: MINGW32
      #
      #- name: Install Qt
      #  uses: jurplel/install-qt-action@v2.5.3
      #  with:
      #    version: ${{ env.QT_VERSION }}
      #    arch:    ${{ env.MINGW_VERSION }}
      #    extra:   --external 7z
      
      - name: tree
        run: |
          where make.exe
          cd \
          tree /F
      - uses: actions/checkout@v2
      - name: build
        run: |
          cd dsda-launcher
          mkdir build
          cd build
          C:\Qt\5.15.2\mingw81_64\bin\qmake.exe ..
          C:\ProgramData\Chocolatey\bin\make.exe
          tree /F
          C:\Qt\5.15.2\mingw81_64\bin\windeployqt.exe dsda-launcher.exe
          Compress-Archive -path .\* -destination .\win.zip
          dir
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dsda-launcher\build\win.zip


