name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: echo "{ACTIONS_ALLOW_UNSECURE_COMMANDS}={true}" >> $GITHUB_ENV

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.5.3
      with:
        version: ${{ env.QT_VERSION }}
        arch:    ${{ env.MINGW_VERSION }}
        extra:   --external 7z

    - uses: actions/checkout@v1
      
    - name: qmake
      run: qmake dsda-launcher/dsda-launcher.pro
        
    - name: make
      run: make
