# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install correct version of mingw
        run: |
          choco uninstall mingw --force
          choco uninstall strawberryperl --force
      - uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW32
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: where
        run: |
          where make.exe
          where qmake.exe
          where mkdir
      - name: build
        run: |
          cd dsda-launcher
          mkdir build
          cd build
          make.exe
          windeployqt dsda-launcher.exe
          Compress-Archive -path .\* -destination .\win.zip
          dir
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dsda-launcher\build\win.zip


